name: cardapio_show
description: Aplicativo para criação e gerenciamento de cardápios digitais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  go_router: ^12.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_colorpicker: ^1.0.3
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  flutter_svg: ^2.0.9
  flutter_markdown: ^0.6.18
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
